apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-hello-world-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-hello-world
  template: # describe the pods
    metadata:
      labels:
        app: second-hello-world
    spec:
      containers:
        - name: hello-container
          image: brunohadlich/hello-world-container:latest