apiVersion: v1
kind: Service
metadata:
  name: app1-clusterip
  namespace: default
spec:
  #ClusterIP is internal to the cluster, it is not exposed to the outside world
  type: ClusterIP
  selector:
    #Select all pods that have at least the label 'app: app1',
    #the pods can have other labels too, that is not a problem
    app: app1
  ports:
    #This service is internal to the cluster, all TCP traffic that hits this service ports
    #79 and 54 will be redirected to the pods that match the previous selector at port 8083.
    #Both service ports 79 and 54 will map to the container port 8083
    - protocol: TCP
      name: port79
      port: 79
      targetPort: 8083
    - protocol: TCP
      name: port54
      port: 54
      targetPort: 8083