apiVersion: v1
kind: Service
metadata:
  name: app2-nodeport
  namespace: default
spec:
  #NodePort is exposed to the outside world through spec.ports.[].nodePort
  type: NodePort
  selector:
    #Select all pods that have at least the label 'app: app2',
    #the pods can have other labels too, that is not a problem
    app: app2
  ports:
    #All TCP traffic that comes at the 31465 port of the cluster node will be redirected to the service port
    #8085 and the pods that are connected to this service through the previous selector will receive this
    #traffic at port 8089
    - protocol: TCP
      nodePort: 31465
      port: 8085
      targetPort: 8089