O0: main.c
	gcc -mavx -O0 -o main main.c my_intrinsics.c

O1: main.c
	gcc -mavx -O1 -o main main.c my_intrinsics.c

O2: main.c
	gcc -mavx -O2 -o main main.c my_intrinsics.c

O3: main.c
	gcc -mavx -O3 -o main main.c my_intrinsics.c
