all:
	go build assertions.go
	go build closures.go
	go build error.go
	go build goroutines_channels.go
	go build goroutines_select_default_example.go
	go build goroutines_select_example.go
	go build interfaces.go
	go build io.go
	go build maps.go
	go build methods.go
	go build slices.go
